const filterActionTypes = {
  RESET_FILTER: "RESET_FILTER",
  SET_GAME_TIME: "SET_GAME_TIME",
  SET_PLAYERS_COUNT: "SET_PLAYERS_COUNT",
  TOGGLE_IS_IN_STOCK: "TOGGLE_IS_IN_STOCK",
  SET_PRICE_VALUES: "SET_PRICE_VALUES",
  SET_DEBOUNCED_PRICE_VALUES: "SET_DEBOUNCED_PRICE_VALUES",
  SET_SHOW_FILTER: "SET_SHOW_FILTER",
  RESET_PRICE_LIMITS: "RESET_PRICE_LIMITS",
  SET_ITEMS_FOUND: "SET_ITEMS_FOUND",
};

export default filterActionTypes;
