const cartActionTypes = {
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  TOGGLE_CART_DROPDOWN_VISIBILITY: "TOGGLE_CART_DROPDOWN_VISIBILITY",
  HIDE_CART_DROPDOWN: "HIDE_CART_DROPDOWN",
  CLEAR_CART: "CLEAR_CART",
  FETCH_USER_CART_ITEMS_SUCCESS: "FETCH_USER_CART_ITEMS_SUCCESS",
  FETCH_USER_CART_ITEMS_FAILURE: "FETCH_USER_CART_ITEMS_FAILURE",
  UPDATE_USER_CART_ITEMS_SUCCESS: "UPDATE_USER_CART_ITEMS_SUCCESS",
  UPDATE_USER_CART_ITEMS_FAILURE: "UPDATE_USER_CART_ITEMS_FAILURE",
};

export default cartActionTypes;
