const lightBoxActionTypes = {
  SET_CURRENT_IMAGE_INDEX: "SET_CURRENT_IMAGE_INDEX",
  INCREASE_CURRENT_IMAGE_INDEX: "INCREASE_CURRENT_IMAGE_INDEX",
  DECREASE_CURRENT_IMAGE_INDEX: "DECREASE_CURRENT_IMAGE_INDEX",
  HIDE_LIGHT_BOX: "HIDE_LIGHT_BOX",
  SHOW_LIGHT_BOX: "SHOW_LIGHT_BOX",
};

export default lightBoxActionTypes;
