const searchActionTypes = {
  HIDE_SEARCH_FIELD: "HIDE_SEARCH_FIELD",
  TOGGLE_SEARCH_FIELD_VISIBILITY: "TOGGLE_SEARCH_FIELD_VISIBILITY",
  SET_CURRENT_LIST_ITEM_INDEX: "SET_CURRENT_LIST_ITEM_INDEX",
  INCREASE_CURRENT_LIST_ITEM_INDEX: "INCREASE_CURRENT_LIST_ITEM_INDEX",
  DECREASE_CURRENT_LIST_ITEM_INDEX: "DECREASE_CURRENT_LIST_ITEM_INDEX",
  RESET_CURRENT_LIST_ITEM_INDEX: "RESET_CURRENT_LIST_ITEM_INDEX",
  SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
  HIDE_SEARCH_DROPDOWN: "HIDE_SEARCH_DROPDOWN",
  SHOW_SEARCH_DROPDOWN: "SHOW_SEARCH_DROPDOWN",
  HIDE_SEARCH_MODAL: "HIDE_SEARCH_MODAL",
  SHOW_SEARCH_MODAL: "SHOW_SEARCH_MODAL",
};

export default searchActionTypes;
