const favoritesActionTypes = {
  TOGGLE_FAVORITE: "TOGGLE_FAVORITE",
  CLEAR_FAVORITES: "CLEAR_FAVORITES",
  FETCH_USER_FAVORITE_ITEMS_SUCCESS: "FETCH_USER_FAVORITE_ITEMS_SUCCESS",
  FETCH_USER_FAVORITE_ITEMS_FAILURE: "FETCH_USER_FAVORITE_ITEMS_FAILURE",
  UPDATE_USER_FAVORITE_ITEMS_SUCCESS: "UPDATE_USER_FAVORITE_ITEMS_SUCCESS",
  UPDATE_USER_FAVORITE_ITEMS_FAILURE: "UPDATE_USER_FAVORITE_ITEMS_FAILURE",
};

export default favoritesActionTypes;
