export const COLLECTION_DATA = {
  currency: "\u20bd",
  collection: [
    {
      id: 1,
      img: "https://via.placeholder.com/200",
      title: "Азул",
      price: 2740,
      alias: "azul",
      copies_sold: 870,
      num_user_ratings: 125,
      average_user_rating: 4.65,
      min_players: 2,
      max_players: 4,
      min_playtime: 30,
      max_playtime: 45,
      min_age: 8,
      published: "02/2020",
      discount_pirce: "",
      categories: ["abstract-logic", "family"],
      quantity: 221,
    },
    {
      id: 2,
      img: "https://via.placeholder.com/200",
      title: "Коридор",
      price: 2200,
      alias: "quoridor",
      copies_sold: 200,
      num_user_ratings: 25,
      average_user_rating: 4,
      min_players: 2,
      max_players: 4,
      min_playtime: 15,
      max_playtime: 15,
      min_age: 8,
      published: "04/2015",
      discount_pirce: "",
      categories: ["abstract-and-logic", "strategic"],
      quantity: 0,
    },
    {
      id: 3,
      img: "https://via.placeholder.com/200",
      title: "Саграда",
      price: 2300,
      alias: "sagrada",
      copies_sold: 340,
      num_user_ratings: 44,
      average_user_rating: 4.1,
      min_players: 1,
      max_players: 4,
      min_playtime: 30,
      max_playtime: 45,
      min_age: 14,
      published: "04/2014",
      discount_pirce: "",
      categories: ["abstract-and-logic", "family"],
      quantity: 123,
    },
    {
      id: 4,
      img: "https://via.placeholder.com/200",
      title: "Капитан Сонар",
      price: 3100,
      alias: "captain-sonar",
      copies_sold: 670,
      num_user_ratings: 56,
      average_user_rating: 4.4,
      min_players: 2,
      max_players: 8,
      min_playtime: 45,
      max_playtime: 60,
      min_age: 14,
      published: "06/2018",
      discount_pirce: "2800",
      categories: ["cooperative", "party"],
      quantity: 56,
    },
    {
      id: 5,
      img: "https://via.placeholder.com/200",
      title: "Пандемия. Наследие",
      price: 4630,
      alias: "pandemic-legacy",
      copies_sold: 900,
      num_user_ratings: 105,
      average_user_rating: 4.49,
      min_players: 2,
      max_players: 4,
      min_playtime: 60,
      max_playtime: 60,
      min_age: 13,
      published: "02/2017",
      discount_pirce: "",
      categories: ["cooperative"],
      quantity: 12,
    },
    {
      id: 6,
      img: "https://via.placeholder.com/200",
      title: "Остров Духов",
      price: 4950,
      alias: "spirit-island",
      copies_sold: 860,
      num_user_ratings: 95,
      average_user_rating: 4.3,
      min_players: 1,
      max_players: 4,
      min_playtime: 90,
      max_playtime: 120,
      min_age: 13,
      published: "04/2020",
      discount_pirce: "",
      categories: ["cooperative", "family"],
      quantity: 0,
    },
    {
      id: 7,
      img: "https://via.placeholder.com/200",
      title: "Контейнер",
      price: 4400,
      alias: "container",
      copies_sold: 420,
      num_user_ratings: 54,
      average_user_rating: 4.12,
      min_players: 3,
      max_players: 5,
      min_playtime: 75,
      max_playtime: 90,
      min_age: 13,
      published: "01/2016",
      discount_pirce: "",
      categories: ["economic", "strategic"],
      quantity: 10,
    },
    {
      id: 8,
      img: "https://via.placeholder.com/200",
      title: "Энергосеть",
      price: 4530,
      alias: "power-grid",
      copies_sold: 560,
      num_user_ratings: 63,
      average_user_rating: 4.43,
      min_players: 2,
      max_players: 6,
      min_playtime: 120,
      max_playtime: 120,
      min_age: 12,
      published: "01/2010",
      discount_pirce: "3500",
      categories: ["economic", "strategic"],
      quantity: 0,
    },
    {
      id: 9,
      img: "https://via.placeholder.com/200",
      title: "Роскошь",
      price: 2350,
      alias: "splendor",
      copies_sold: 760,
      num_user_ratings: 103,
      average_user_rating: 4.51,
      min_players: 2,
      max_players: 4,
      min_playtime: 30,
      max_playtime: 30,
      min_age: 10,
      published: "05/2013",
      discount_pirce: "1900",
      categories: ["economic", "family"],
      quantity: 420,
    },
    {
      id: 10,
      img: "https://via.placeholder.com/200",
      title: "Семь чудес",
      price: 2720,
      alias: "seven-wonders",
      copies_sold: 980,
      num_user_ratings: 99,
      average_user_rating: 4.6,
      min_players: 2,
      max_players: 7,
      min_playtime: 30,
      max_playtime: 30,
      min_age: 10,
      published: "08/2010",
      discount_pirce: "2200",
      categories: ["family", "strategic"],
      quantity: 341,
    },
    {
      id: 11,
      img: "https://via.placeholder.com/200",
      title: "Джайпур",
      price: 1730,
      alias: "jaipur",
      copies_sold: 330,
      num_user_ratings: 68,
      average_user_rating: 4.11,
      min_players: 2,
      max_players: 2,
      min_playtime: 30,
      max_playtime: 30,
      min_age: 12,
      published: "02/2020",
      discount_pirce: "",
      categories: ["family", "two-players"],
      quantity: 110,
    },
    {
      id: 12,
      img: "https://via.placeholder.com/200",
      title: "Крылья",
      price: 3950,
      alias: "wingspan",
      copies_sold: 880,
      num_user_ratings: 98,
      average_user_rating: 4.48,
      min_players: 1,
      max_players: 5,
      min_playtime: 40,
      max_playtime: 70,
      min_age: 10,
      published: "01/2020",
      discount_pirce: "",
      categories: ["family", "strategic"],
      quantity: 321,
    },
    {
      id: 13,
      img: "https://via.placeholder.com/200",
      title: "Кодовые имена",
      price: 1250,
      alias: "codenames",
      copies_sold: 930,
      num_user_ratings: 100,
      average_user_rating: 4.61,
      min_players: 2,
      max_players: 8,
      min_playtime: 15,
      max_playtime: 15,
      min_age: 14,
      published: "08/2016",
      discount_pirce: "",
      categories: ["party"],
      quantity: 331,
    },
    {
      id: 14,
      img: "https://via.placeholder.com/200",
      title: "Диксит",
      price: 2500,
      alias: "dixit",
      copies_sold: 910,
      num_user_ratings: 114,
      average_user_rating: 4.62,
      min_players: 3,
      max_players: 6,
      min_playtime: 30,
      max_playtime: 30,
      min_age: 8,
      published: "04/2014",
      discount_pirce: "",
      categories: ["party"],
      quantity: 451,
    },
    {
      id: 15,
      img: "https://via.placeholder.com/200",
      title: "Виноделие",
      price: 5400,
      alias: "viticulture",
      copies_sold: 770,
      num_user_ratings: 120,
      average_user_rating: 4.49,
      min_players: 1,
      max_players: 6,
      min_playtime: 45,
      max_playtime: 90,
      min_age: 13,
      published: "03/2020",
      discount_pirce: "",
      categories: ["strategic"],
      quantity: 156,
    },
    {
      id: 16,
      img: "https://via.placeholder.com/200",
      title: "Лондон",
      price: 1800,
      alias: "london",
      copies_sold: 380,
      num_user_ratings: 20,
      average_user_rating: 4,
      min_players: 2,
      max_players: 4,
      min_playtime: 90,
      max_playtime: 90,
      min_age: 13,
      published: "02/2020",
      discount_pirce: "",
      categories: ["strategic"],
      quantity: 65,
    },
    {
      id: 17,
      img: "https://via.placeholder.com/200",
      title: "Серп",
      price: 5410,
      alias: "scythe",
      copies_sold: 740,
      num_user_ratings: 130,
      average_user_rating: 4.51,
      min_players: 1,
      max_players: 5,
      min_playtime: 90,
      max_playtime: 115,
      min_age: 14,
      published: "08/2019",
      discount_pirce: "",
      categories: ["strategic"],
      quantity: 71,
    },
    {
      id: 18,
      img: "https://via.placeholder.com/200",
      title: "Пэчворк",
      price: 850,
      alias: "patchwork",
      copies_sold: 570,
      num_user_ratings: 39,
      average_user_rating: 4.21,
      min_players: 2,
      max_players: 2,
      min_playtime: 15,
      max_playtime: 30,
      min_age: 8,
      published: "06/2018",
      discount_pirce: "",
      categories: ["two-players"],
      quantity: 81,
    },
    {
      id: 19,
      img: "https://via.placeholder.com/200",
      title: "Покорение Марса",
      price: 3720,
      alias: "terraforming-mars",
      copies_sold: 840,
      num_user_ratings: 134,
      average_user_rating: 4.59,
      min_players: 1,
      max_players: 5,
      min_playtime: 120,
      max_playtime: 120,
      min_age: 12,
      published: "04/2019",
      discount_pirce: "",
      categories: ["strategic"],
      quantity: 82,
    },
    {
      id: 20,
      img: "https://via.placeholder.com/200",
      title: "Конкордия",
      price: 3100,
      alias: "concordia",
      copies_sold: 410,
      num_user_ratings: 49,
      average_user_rating: 4.32,
      min_players: 2,
      max_players: 5,
      min_playtime: 100,
      max_playtime: 100,
      min_age: 13,
      published: "04/2018",
      discount_pirce: "",
      categories: ["strategic"],
      quantity: 23,
    },
    {
      id: 21,
      img: "https://via.placeholder.com/200",
      title: "Терра Мистика",
      price: 3880,
      alias: "terra-mystica",
      copies_sold: 680,
      num_user_ratings: 14,
      average_user_rating: 4.43,
      min_players: 2,
      max_players: 5,
      min_playtime: 60,
      max_playtime: 150,
      min_age: 12,
      published: "04/2019",
      discount_pirce: "3100",
      categories: ["strategic"],
      quantity: 11,
    },
    {
      id: 22,
      img: "https://via.placeholder.com/200",
      title: "Великий западный путь",
      price: 2150,
      alias: "great-western-trail",
      copies_sold: 790,
      num_user_ratings: 119,
      average_user_rating: 4.34,
      min_players: 2,
      max_players: 4,
      min_playtime: 75,
      max_playtime: 150,
      min_age: 12,
      published: "09/2019",
      discount_pirce: "",
      categories: ["strategic"],
      quantity: 0,
    },
  ],
};
